compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@intlify/unplugin-vue-i18n@*":
    dependencies:
      vite: "*"
  "@pinia/testing@*":
    dependencies:
      vue: "*" 
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
      "@vue/server-renderer": "*"
      vue: "*"
  local-pkg@*:
    dependencies:
      jsdom: "*"
  mocha@*:
    dependencies:
      ts-node: "*"
      tsconfig-paths: "*"
  vue-demi@*:
    dependencies:
      vue: "*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
