compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
  local-pkg@*:
    dependencies:
      jsdom: "*"
  mocha@*:
    dependencies:
      ts-node: "*"
      tsconfig-paths: "*"
  vue-demi@*:
    dependencies:
      vue: "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
