yarnPath: .yarn/releases/yarn-3.3.1.cjs

packageExtensions:
  "local-pkg@*":
    dependencies:
      "jsdom": "*"
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*" 
  "vue-demi@*":
    dependencies:
      "vue": "*" 